# Generated by Django 4.0.6 on 2022-08-24 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0021_codebaseresource_package_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='extracted_from',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_to', to='scanpipe.codebaseresource'),
        ),
    ]
