# Generated by Django 4.0.6 on 2022-08-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0021_remove_discoveredpackage_dependencies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discovereddependency',
            options={'ordering': ['-is_runtime', '-is_resolved', 'is_optional', 'dependency_uid'], 'verbose_name': 'discovered dependency', 'verbose_name_plural': 'discovered dependencies'},
        ),
        migrations.AlterField(
            model_name='discovereddependency',
            name='extracted_requirement',
            field=models.CharField(blank=True, help_text='The version requirements of this dependency.', max_length=256),
        ),
    ]
